export const INFORMACAO_ORCAMENTO = "INFORMACAO_ORCAMENTO"
export const CADASTRO_UNIDADES = "CADASTRO_UNIDADES"
export const CADASTRO_ARTEFATOS = "CADASTRO_ARTEFATOS"
export const FINALIZAR = "FINALIZAR"
